system:
  type: viblad
  params:
    V_max: 10
    omega_cm: 2349.1
    delta_omega_cm: 25.0
    input_units: "cm^-1"
    output_units: "rad/fs"
    pol_initial: [1.0, 0.0]
states:
  initial: [0]
  target:  [5]
time:
  total_fs: 500.0
  dt_fs: 0.1
  sample_stride: 1
algorithm:
  selected: krotov
algorithms:
  krotov:
    max_iter: 1000
    convergence_tol: 1.0e-18
    lambda_a: 1.0e-20
    target_fidelity: 1.0
    control_axes: "zx"
    duration_initial: 200.0
    pol_initial: [1.0, 0.0]
plot:
  save_fig: true
  spectrum: true
  spectrogram: true
output:
  dir: "examples/figures"


