system:
  type: viblad
  params:
    V_max: 5
    omega_cm: 2349.1
    delta_omega_cm: 25.0
    input_units: "cm^-1"
    output_units: "rad/fs"
states:
  initial: [0]
  target:  [3]
time:
  total_fs: 1000.0
  dt_fs: 0.1
  sample_stride: 1
algorithm:
  selected: krotov
algorithms:
  krotov:
    max_iter: 150
    convergence_tol: 1.0e-18
    lambda_a: 1.0e-20
    target_fidelity: 1.0
    pol_initial: [1.0, 0.0]
    control_axes: "zx"
    duration_initial: 400.0
    spectrum_constraints:
      method: "monotonic_kernel"
      bands:
        - [2325, 100.0]   # [center_cm^-1, FWHM_cm^-1]
      units: "cm^-1"
      mode: "pass"
      combine: "max"
      fwhm: true
      alpha_scale: 10.0
plot:
  save_fig: true
  spectrum: true
  spectrogram: true
output:
  dir: "examples/figures"

